### ISSUE TITLE
CD3DDeviceLevel1_PresentSwapChain_Hook doesn't get called

### ISSUE THREAD

**Issue by ANewTypeNoob** [wongfei/dwm_overlay#1]
![1](https://user-images.githubusercontent.com/48608592/76701408-490e7300-6697-11ea-9054-3fbaf53face6.PNG)

**Comment by wongfei** [comment]
win version / VM ?

**Comment by ANewTypeNoob** [comment]
![image](https://user-images.githubusercontent.com/48608592/76702555-0a7db600-66a1-11ea-97b2-950f0732d900.png)

**Comment by wongfei** [comment]
updated to 10.0.18363.720

**Comment by w3lld0ne** [comment]
very sad such a nice info is now public and will be used by every second “haxor”... :/

**Comment by ANewTypeNoob** [comment]
Appreciating your help
