### ISSUE TITLE
Please include required libraries to $(SolutionDir)polyhook2\_bin\x64

### ISSUE THREAD

**Issue by JonathanXLin** [wongfei/dwm_overlay#3]
asmjit.lib;
capstone.lib;
Zydis.lib;
PolyHook_2.lib;
kernel32.lib;
user32.lib;
gdi32.lib;
winspool.lib;
comdlg32.lib;
advapi32.lib;
shell32.lib;
ole32.lib;
oleaut32.lib;
uuid.lib;
odbc32.lib;
odbccp32.lib

**Comment by wongfei** [comment]
8aeaa275f62fbc2c7013e8364e4bebc343edba84

**Comment by JonathanXLin** [comment]
Thank you! I really appreciate it.
